packages:
  - apps/*
  - packages/*

allowBuilds:
  '@clerk/shared': false
  '@sentry/cli': false
  '@swc/core': false
  '@tailwindcss/oxide': false
  core-js-pure: false
  esbuild: false
  sharp: false

ignoredBuiltDependencies:
  - protobufjs
